apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: HTTPS
      # Use this annotation (which must match a service name) to route traffic to HTTP2 backends.
      alb.ingress.kubernetes.io/conditions.argogrpc: |
        [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "Content-Type", "values":["application/grpc"]}}]
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
      cert-manager.io/issuer: letsencrypt-dns01-staging
      alb.ingress.kubernetes.io/scheme: internet-facing
      kubernetes.io/ingress.class: alb
    name: argocd
    namespace: argocd
spec:
    rules:
    - host: argocd.themulticlouding.com
      http:
        paths:
        - path: /
          backend:
            service:
              name: argogrpc
              port:
                number: 443
          pathType: Prefix
        - path: /
          backend:
            service:
              name: argocd-eks-server
              port:
                number: 443
          pathType: Prefix
    tls:
    - hosts:
      - argocd.themulticlouding.com
      secretName: argocd-v1-themulticlouding-io-key-pair
