name: AWS-EKS-DEPLOY

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install terragrunt on ubuntu
        run: |
          curl -Ls https://github.com/gruntwork-io/terragrunt/releases/download/v0.48.0/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod a+x /usr/local/bin/terragrunt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terragrunt Init
        working-directory: dev/
        run: |
          terragrunt run-all init
        
      - name: Terraform Format
        working-directory: dev/
        run: terragrunt run-all fmt

      - name: Terraform Plan
        working-directory: dev/
        run: terragrunt run-all plan

      - name: Terraform Apply
        working-directory: dev/
        run: terragrunt run-all apply
