name: AWS-EKS-DEPLOY

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.7.0 # this action will configure git to use the right SSH key per each repository. 
        with:
         ssh-private-key: |
          ${{ secrets.INFRASTRUCTURE_MODULES_PRIVATEKEY}}
         repo-mappings: |
          git@github.com:Mohit-Verma-1688/infrastucture-modules.git
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive # this is important not to forget
          
      - name: Install terragrunt on ubuntu
        run: |
          curl -Ls https://github.com/gruntwork-io/terragrunt/releases/download/v0.48.0/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod a+x /usr/local/bin/terragrunt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terragrunt Init
        working-directory: dev/
        run: |
          terragrunt run-all init
        
      - name: Terraform Format
        working-directory: dev/
        run: terragrunt run-all fmt

      - name: Terraform Plan
        working-directory: dev/
        run: terragrunt run-all plan
