name: AWS-EKS-DEPLOY

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1
  tf_version: 'latest'
  tg_version: 'latest'
  tf_working_dir: './dev'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./dev
    steps:
      - uses: webfactory/ssh-agent@v0.7.0 # this action will configure git to use the right SSH key per each repository. 
        with:
         ssh-private-key: |
          ${{ secrets.INFRASTRUCTURE_MODULES_PRIVATEKEY}}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive # this is important not to forget
          
#      - name: Install terragrunt on ubuntu
#        run: |
#          curl -Ls https://github.com/gruntwork-io/terragrunt/releases/download/v0.48.0/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
#          chmod a+x /usr/local/bin/terragrunt

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #role-to-assume: arn:aws:iam::833192599359:role/terraform
          #role-session-name: devlab
          aws-region: us-east-1
          #role-skip-session-tagging: true
          #role-duration-seconds: 1200
          
#      - name: Setup Terragrunt
#        uses: autero1/action-terragrunt@v1.1.0
#        with:
#          terragrunt_version: 0.48.0
        
          
#      - name: Setup Terraform
#        uses: hashicorp/setup-terraform@v2
#        with: 
#         terraform_wrapper: false
         
#      - name: Interact with Terragrunt
#        run: terragrunt --version
        
#      - name: checking for the credentials
#        run: |
#         echo $AWS_SECRET_ACCESS_KEY
        
#      - name: run terragrunt init
#        env:
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        run: terragrunt run-all init --terragrunt-non-interactive
        
          

          
      - uses: the-commons-project/terragrunt-github-actions@master
        name: Terragrunt init
        with: 
          tf_actions_version: ${{ env.tf_version }}
          tg_actions_version: ${{ env.tg_version }}
          tf_actions_binary: 'terragrunt run-all'
          tf_actions_subcommand: 'init'
#          tf_actions_working_dir: ${{ env.tf_working_dir }}
          tf_actions_comment: true
        env:
#          AWS_DEFAULT_REGION: "us-east-1"
#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          GITHUB_TOKEN: ${{ secrets.PRIVATEGIT_TOKEN }}
          
#      - uses: the-commons-project/terragrunt-github-actions@master
#        name: Terragrunt validate
#        with: 
#          tf_actions_version: ${{ env.tf_version }}
#          tg_actions_version: ${{ env.tg_version }}
#          tf_actions_binary: 'terragrunt'
#          tf_actions_subcommand: 'validate'
#          tf_actions_working_dir: ${{ env.tf_working_dir }}
#          tf_actions_comment: true
          
#     - uses: the-commons-project/terragrunt-github-actions@master
#        name: Terragrunt plan
#        with: 
#          tf_actions_version: ${{ env.tf_version }}
#          tg_actions_version: ${{ env.tg_version }}
#          tf_actions_binary: 'terragrunt'
#          tf_actions_subcommand: 'plan'
#          tf_actions_working_dir: ${{ env.tf_working_dir }}
#          tf_actions_comment: true
               
        
#      - name: Terraform Format
#        working-directory: dev/
#        run: terragrunt run-all fmt --terragrunt-non-interactive
#
#      - name: Terraform Plan
#        working-directory: dev/
#        run: terragrunt run-all plan --terragrunt-non-interactive
